# src/core/constants.py

from __future__ import annotations


DEFAULT_OUTPUTS_ROOT = "outputs"
DEFAULT_MEMORY_DIRNAME = "memory"
DEFAULT_LOGS_DIRNAME = "logs"

DEFAULT_RANDOM_SEED = 42
DEFAULT_TOP_K = 3

DEFAULT_SELECTOR_MAX_LEN = 384
DEFAULT_SELECTOR_ALPHA = 0.5
DEFAULT_SELECTOR_NN_EVAL_SAMPLES = 200

DEFAULT_JSON_INDENT = 2

DEFAULT_EVENT_LOG_FILENAME = "events.jsonl"
DEFAULT_RUN_LOG_FILENAME = "run.log"
DEFAULT_METRICS_JSONL_FILENAME = "metrics.jsonl"
DEFAULT_LATEST_METRICS_FILENAME = "latest_metrics.json"

DEFAULT_SELECTED_CHANNELS_FILENAME = "selected_channels.json"
DEFAULT_BUILD_META_FILENAME = "build_meta.json"
DEFAULT_MEMORY_BANK_FILENAME = "memory_bank.jsonl"
DEFAULT_TS_INDEX_FILENAME = "index_ts.pkl"
DEFAULT_TEXT_INDEX_FILENAME = "index_text.pkl"
DEFAULT_STAT_INDEX_FILENAME = "index_stat.pkl"